### ISSUE TITLE
Service Mesh Interface

### ISSUE THREAD

**Issue by craigbox** [servicemesh-es/servicemesh.es#101]
Your comparison talks about the Service Mesh Interface, which has [effectively been deprecated](https://smi-spec.io/blog/announcing-smi-gateway-api-gamma/) in favour of work on the Gateway API.

The reference implementation of SMI, OpenServiceMesh, [has been archived](https://openservicemesh.io/blog/osm-project-update/).

It might be a good idea to replace SMI with Gateway API throughout?

**Comment by MarcoSteinke** [comment]
Thank you for this issue. It is definitely a good idea to change the presentation of the comparison in a way, that on the one hand visitors will get information on the archiving of OSM and on the other hand find an alternative (Gateway API) in the comparison.

**Comment by craigbox** [comment]
(I wasn't implying my OSM PR solved the issue. Did you address it some other way?)

**Comment by MarcoSteinke** [comment]
For me, your PR solved the issue because it removed OSM from the list of implementations and the tables. I will push something which adds the Gateway API to the listing and also notifies visitors about the replacement. 👍🏻
