### ISSUE TITLE
Multi-cloud / multi-cluster section

### ISSUE THREAD

**Issue by blake** [servicemesh-es/servicemesh.es#23]
Hi,

Multi-cluster / multi-cloud seem to be of interest to enterprises evaluating service mesh solutions. It might be worthwhile to add a column/section highlighting the multi-cloud features available in the various mesh solutions.

**Comment by HPrinz** [comment]
Yes, I agree! We already have an internal draft for those feature dimensions:
- Multi-Cluster Mesh (Control and Observe multiple clusters)
- Mesh Expansion (extend the Mesh through Containers outside the Cluster) 
I'll add those soon

**Comment by HPrinz** [comment]
"Mesh Expansion" and "Multi-Cluster Mesh" were added to a new block "Platform". 
Feedback is very welcome :)
