### ISSUE TITLE
Istio's Service Mesh Interface Compatibility (except for metrics for now)

### ISSUE THREAD

**Issue by tkms0106** [servicemesh-es/servicemesh.es#41]
Now the website is saying simply "YES".
<img width=200 src=https://user-images.githubusercontent.com/23391543/100445380-59b12d00-30f0-11eb-8bca-9593fe1ddfb2.png />

And the reason behind the answer "YES" is [smi-adapter-istio](https://github.com/servicemeshinterface/smi-adapter-istio) implementation.

But I guess it's slightly misleading because of following issues.
https://github.com/servicemeshinterface/smi-adapter-istio/issues/94
https://github.com/servicemeshinterface/smi-adapter-istio/issues/93
https://github.com/servicemeshinterface/smi-adapter-istio/issues/74

If there is no problem, I will try to add some annotations to these rows.

**Comment by HPrinz** [comment]
That would be great, thank you. I think it adds value to make clear that it's inofficial/3rd party support

**Comment by tkms0106** [comment]
I also visited these links.
<img width=400 src=https://user-images.githubusercontent.com/23391543/100454625-9e44c480-3100-11eb-9249-18d53641a442.png />

I intend to add the same comment to these rows.
