### ISSUE TITLE
Describe what the "Cloud Integrations" row means

### ISSUE THREAD

**Issue by HPrinz** [servicemesh-es/servicemesh.es#49]
It is currently not clear, what a Cloud Integration means and what it could add to a custom installation

**Comment by wmorgan** [comment]
In particular, is this a measure of "is it easy to install this on this cloud provider", or is it a measure of "does this cloud provider explicitly say they support this"? If the latter, do references in docs count? Does a third-party plugin in some kind of marketplace for that provider count?

**Comment by HPrinz** [comment]
Hm. Good questions. The row was intended to show support & automation from the cloud-provider side (e.g. installation and upgrades). 
But I agree that installation docs are important resources, too. So what about we add a row with "Installation Docs" that can list links for different Cloud Providers or just say "Any cluster" with one link?

**Comment by MarcoSteinke** [comment]
From my understanding of this thread, the row was integrated with the title "Tutorial". Thus I will be closing this issue.

![image](https://github.com/servicemesh-es/servicemesh.es/assets/49523050/a95b3967-5922-4f95-85fb-c65540359af1)
