### ISSUE TITLE
gRPC health checking

### ISSUE THREAD

**Issue by schwichti** [servicemesh-es/servicemesh.es#56]
Hello,
are you aware of a service mesh implementation that supports health checking of gRPC services? In Kubernetes, you can configure [liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), but in case of gRPC you have to [implement it yourself](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/). My question is if you know a service mesh implementation that comes with sidecars that have such a functionality built-in.

**Comment by MarcoSteinke** [comment]
Hello @schwichti ,
Sorry for not answering this issue for such a long time. Maybe you forgot about your question, maybe you answered it yourself. From today's perspective I can tell you that [Istio](https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/) and [nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/grpc-health-check/) have gRPC health checks as far as I can see. For nginx I have to assume that the gRPC health check is also implemented in their Service Mesh.
