### ISSUE TITLE
Add new cilium service mesh to comparison

### ISSUE THREAD

**Issue by Shocktrooper** [servicemesh-es/servicemesh.es#76]
https://www.cncf.io/blog/2022/07/20/cilium-1-12-ga-cilium-service-mesh-and-other-major-new-features-for-enterprise-kubernetes/
https://isovalent.com/blog/post/cilium-release-112/

**Comment by HPrinz** [comment]
This has been added some time ago already, see https://github.com/servicemesh-es/servicemesh.es/commit/781352c75fcd52410bf3950a31a8e6efad2142c6. Closing this
