### ISSUE TITLE
AWS App Mesh info correction

### ISSUE THREAD

**Issue by yubingjiaocn** [servicemesh-es/servicemesh.es#79]
Hi, 

I found some outdated info on AWS App Mesh on https://servicemesh.es/. Detailed list is below:  

1. For _Ingress Controller_ section, AWS App Mesh supports Envoy based [Virtual Gateway](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_gateways.html). This gateway can also be exposed by AWS Elastic Load Balancer created by [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/)

2. For _Used in production_ section, AWS App Mesh is [generally available](https://aws.amazon.com/about-aws/whats-new/2019/03/aws-app-mesh-is-now-generally-available/) on 2019/05/27 and have many [customer references](https://aws.amazon.com/app-mesh/customers/). I suppose it can be considered production ready. 

3. For _Multi-Cluster Mesh_ section, since AWS App Mesh has a fully hosted control plane, user can create mesh cross EKS cluster via AWS Cloud Map. See this [blog post](https://aws.amazon.com/blogs/containers/cross-amazon-eks-cluster-app-mesh-using-aws-cloud-map/) for detail. 

4. For _Compatible Tracing-Backends_ section, besides AWS X-Ray, AWS App Mesh also supports Jaeger and DataDog for tracing. See this [doc](https://docs.aws.amazon.com/app-mesh/latest/userguide/tracing.html#jaeger)

Could you please help me correct these items? Thank you.

**Comment by HPrinz** [comment]
Thank you for this helpful issue and your patience! 🙏
